VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "hNFe4_Doc_ide"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit


Public m_cNF As String
Public m_cUF As String
Public m_mod As String
Public m_serie  As String
Public m_nNF As String
Public m_dhEmi As Date

Public m_cMunFG  As String

Public m_dhSaiEnt
'Public m_tpNF>1</tpNF>
'Public m_idDest>2</idDest>
'Public m_cMunFG>4208203</cMunFG>
'Public m_tpImp>1</tpImp>
Public m_tpEmis As String
'Public m_cDV>3</cDV>
'Public m_tpAmb>2</tpAmb>
'Public m_finNFe>1</finNFe>
'Public m_indFinal>1</indFinal>
'Public m_indPres>9</indPres>
'Public m_procEmi>0</procEmi>
'Public m_verProc>2.53</verProc>

