VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "hNFe4_Doc_total"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit


Public m_vBC As Double '>686.10</vBC>")
Public m_vICMS As Double '>48.03</vICMS>")
Public m_vICMSDeson As Double '>0</vICMSDeson>")
Public m_vFCPUFDest As Double '>0</vFCPUFDest>")
Public m_vICMSUFDest As Double '>27.44</vICMSUFDest>")
Public m_vICMSUFRemet As Double '>41.16</vICMSUFRemet>")
Public m_vBCST As Double '>0</vBCST>")
Public m_vST As Double '>0</vST>")
Public m_vProd As Double '>520.00</vProd>")
Public m_vFrete As Double '>166.10</vFrete>")
Public m_vSeg As Double '>0</vSeg>")
Public m_vDesc As Double '>0</vDesc>")
Public m_vII As Double '>'0</vII>")
Public m_vIPI As Double '>0</vIPI>")
Public m_vPIS As Double '>'11.32</vPIS>")
Public m_vCOFINS As Double '>52.14</vCOFINS>")
Public m_vOutro As Double '>0</vOutro>")
Public m_vNF As Double '>686.10</vNF>")
Public m_vTotTrib As Double '>317.39</vTotTrib>")
    
Sub Clear()
m_vBC = 0 '>686.10</vBC>")
m_vICMS = 0 '>48.03</vICMS>")
m_vICMSDeson = 0 '>0</vICMSDeson>")
m_vFCPUFDest = 0 '>0</vFCPUFDest>")
m_vICMSUFDest = 0 '>27.44</vICMSUFDest>")
m_vICMSUFRemet = 0 '>41.16</vICMSUFRemet>")
m_vBCST = 0 '>0</vBCST>")
m_vST = 0 '>0</vST>")
m_vProd = 0 '>520.00</vProd>")
m_vFrete = 0 '>166.10</vFrete>")
m_vSeg = 0 '>0</vSeg>")
m_vDesc = 0 '>0</vDesc>")
m_vII = 0 '>'0</vII>")
m_vIPI = 0 '>0</vIPI>")
m_vPIS = 0 '>'11.32</vPIS>")
m_vCOFINS = 0 '>52.14</vCOFINS>")
m_vOutro = 0 '>0</vOutro>")
m_vNF = 0 '>686.10</vNF>")
m_vTotTrib = 0 '>317.39</vTotTrib>")
End Sub

