VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "hNFe4_Doc_det_prod"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit


Public m_cProd      As String
Public m_cEAN       As String
Public m_xProd      As String
Public m_NCM        As String
Public m_CFOP       As String
Public m_uCom       As String
Public m_qCom       As Double
Public m_vUnCom     As Double
Public m_vProd      As Double
Public m_cEANTrib   As String
Public m_uTrib      As String
Public m_qTrib      As Double
Public m_vUnTrib    As Double
Public m_vFrete     As Double
Public m_indTot     As Long
Public m_CEST       As String

 
